/// Event-sourced padel scoring engine.
///
/// Design rules (PRD Rischio 1 + acceptance criteria):
/// * The raw event log is the single source of truth.
/// * State is always derived by replaying the log — undo appends an UNDO
///   event and replays, so it works across game/set boundaries by
///   construction.
/// * Derived events (GAME_COMPLETED, SET_COMPLETED, SIDE_CHANGE,
///   MATCH_COMPLETED) are appended for audit/sync but ignored on replay.
///
/// The same replay semantics are ported to Kotlin (Wear OS) and Swift
/// (watchOS); the JSON wire format lives in [MatchEvent].
library;

import '../model/enums.dart';
import '../model/match_event.dart';
import '../model/match_format.dart';
import '../model/score_state.dart';
import '../util/event_id.dart';
import 'point_record.dart';

/// Transition produced by the latest action, used by UIs to trigger
/// haptics: breve = punto, doppia = undo, lunga = game/set (PRD D1).
enum ScoreTransition { point, gameWon, setWon, matchWon, sideChange, undone }

class ScoringResult {
  const ScoringResult({
    required this.state,
    required this.newEvents,
    required this.transitions,
  });

  final MatchState state;
  final List<MatchEvent> newEvents;
  final List<ScoreTransition> transitions;
}

class _UndoResolution {
  const _UndoResolution({required this.cancelled, required this.ignored});

  final Set<int> cancelled;
  final Set<int> ignored;
}

class PadelScoringEngine {
  PadelScoringEngine({
    required this.matchId,
    required this.format,
    this.firstServer = TeamId.a,
    this.duoMode = false,
    this.sourceUserId,
    this.assignedTeam,
    int Function()? clock,
    String Function()? idGenerator,
  }) : _clock = clock ?? (() => DateTime.now().toUtc().millisecondsSinceEpoch),
       _newId = idGenerator ?? generateEventId {
    _recompute();
  }

  /// Rebuild an engine from a persisted/synced event log.
  factory PadelScoringEngine.replay({
    required String matchId,
    required MatchFormat format,
    required List<MatchEvent> events,
    TeamId firstServer = TeamId.a,
    bool duoMode = false,
    String? sourceUserId,
    TeamId? assignedTeam,
    int Function()? clock,
    String Function()? idGenerator,
  }) {
    final engine = PadelScoringEngine(
      matchId: matchId,
      format: format,
      firstServer: firstServer,
      duoMode: duoMode,
      sourceUserId: sourceUserId,
      assignedTeam: assignedTeam,
      clock: clock,
      idGenerator: idGenerator,
    );
    engine._events.addAll(events);
    engine._recompute();
    return engine;
  }

  final String matchId;
  final MatchFormat format;
  final TeamId firstServer;

  /// Duo Mode: every event generated by this engine instance is stamped with
  /// the session flag, the local account and the team assigned to this
  /// device, so the backend can authorize and audit it.
  final bool duoMode;
  final String? sourceUserId;
  final TeamId? assignedTeam;

  final int Function() _clock;
  final String Function() _newId;

  final List<MatchEvent> _events = [];
  late MatchState _state;
  late List<PointRecord> _records;

  List<MatchEvent> get events => List.unmodifiable(_events);
  MatchState get state => _state;
  List<PointRecord> get pointRecords => List.unmodifiable(_records);

  bool get canUndo {
    if (_isSealedByManualFinish) return false;
    return _undoableCount() > 0;
  }

  /// Duo Mode: whether a team-scoped undo would cancel anything, i.e. there
  /// is a not-yet-undone point of [team] in the log.
  bool canUndoTeam(TeamId team) {
    if (_isSealedByManualFinish) return false;
    final resolution = _resolveUndos();
    for (var i = _events.length - 1; i >= 0; i--) {
      final e = _events[i];
      if (resolution.cancelled.contains(i) || resolution.ignored.contains(i)) {
        continue;
      }
      if ((e.type == MatchEventType.pointTeamA && team == TeamId.a) ||
          (e.type == MatchEventType.pointTeamB && team == TeamId.b)) {
        return true;
      }
    }
    return false;
  }

  /// Manual finish seals the match: undoing points under it is not allowed
  /// (would leave a completed match with a rewritten score). Auto-complete
  /// remains undoable so the winning point can reopen the match.
  bool get _isSealedByManualFinish {
    if (!_state.isCompleted) return false;
    final resolution = _resolveUndos();
    for (var i = _events.length - 1; i >= 0; i--) {
      if (resolution.cancelled.contains(i) || resolution.ignored.contains(i)) {
        continue;
      }
      final e = _events[i];
      if (e.type == MatchEventType.matchCompleted) {
        return e.sourceMethod == SourceMethod.manualEdit;
      }
    }
    return false;
  }

  // ---------------------------------------------------------------- actions

  ScoringResult start({
    SourceDevice device = SourceDevice.phone,
    SourceMethod method = SourceMethod.tap,
  }) {
    final e = _make(
      MatchEventType.matchStarted,
      device: device,
      method: method,
    );
    _events.add(e);
    _recompute();
    return ScoringResult(state: _state, newEvents: [e], transitions: const []);
  }

  /// Registers a point. Returns the point event plus any derived events.
  ScoringResult addPoint(
    TeamId team, {
    SourceDevice device = SourceDevice.phone,
    SourceMethod method = SourceMethod.tap,
  }) {
    // A point can be queued by the UI immediately after pause.  Enforce the
    // match lifecycle in the engine as well so delayed/native inputs cannot
    // mutate a paused (or completed) match.
    if (_state.isCompleted || _state.status == MatchStatus.paused) {
      return ScoringResult(
        state: _state,
        newEvents: const [],
        transitions: const [],
      );
    }
    final before = _state.display;
    final e = _make(
      team == TeamId.a ? MatchEventType.pointTeamA : MatchEventType.pointTeamB,
      teamId: team,
      device: device,
      method: method,
      scoreBefore: before,
    );
    _events.add(e);
    final transitions = _recompute();
    final after = _state.display;
    _events[_events.length - 1] = e.copyWith(scoreAfter: after);

    final derived = <MatchEvent>[];
    void derive(MatchEventType t) {
      final d = _make(
        t,
        teamId: team,
        device: device,
        method: SourceMethod.auto,
        scoreBefore: before,
        scoreAfter: after,
      );
      derived.add(d);
      _events.add(d);
    }

    if (transitions.contains(ScoreTransition.gameWon)) {
      derive(MatchEventType.gameCompleted);
    }
    if (transitions.contains(ScoreTransition.setWon)) {
      derive(MatchEventType.setCompleted);
    }
    if (transitions.contains(ScoreTransition.sideChange)) {
      derive(MatchEventType.sideChange);
    }
    if (transitions.contains(ScoreTransition.matchWon)) {
      derive(MatchEventType.matchCompleted);
    }

    return ScoringResult(
      state: _state,
      newEvents: [_events[_events.length - 1 - derived.length], ...derived],
      transitions: transitions,
    );
  }

  /// Undo the last point or manual edit. Always works (acceptance:
  /// "l'undo deve funzionare sempre"), including across game/set borders.
  ///
  /// [team] (Duo Mode): the UNDO only cancels the last point of that team,
  /// so two devices with differently interleaved logs converge to the same
  /// score. Without [team] the behaviour is the classic global undo.
  ScoringResult undo({
    TeamId? team,
    SourceDevice device = SourceDevice.phone,
    SourceMethod method = SourceMethod.tap,
  }) {
    if (_state.status == MatchStatus.paused) {
      return ScoringResult(
        state: _state,
        newEvents: const [],
        transitions: const [],
      );
    }
    if (team == null ? !canUndo : !canUndoTeam(team)) {
      return ScoringResult(
        state: _state,
        newEvents: const [],
        transitions: const [],
      );
    }
    final e = _make(
      MatchEventType.undo,
      teamId: team,
      device: device,
      method: method,
      scoreBefore: _state.display,
    );
    _events.add(e);
    _recompute();
    _events[_events.length - 1] = e.copyWith(scoreAfter: _state.display);
    return ScoringResult(
      state: _state,
      newEvents: [_events.last],
      transitions: const [ScoreTransition.undone],
    );
  }

  ScoringResult pause({SourceDevice device = SourceDevice.phone}) =>
      _statusEvent(MatchEventType.matchPaused, device);

  ScoringResult resume({SourceDevice device = SourceDevice.phone}) =>
      _statusEvent(MatchEventType.matchResumed, device);

  /// Explicitly end the match (training mode, or abandon with a winner).
  /// No-op when already completed (aligned with watch ports).
  ScoringResult finish({
    TeamId? winner,
    SourceDevice device = SourceDevice.phone,
  }) {
    if (_state.isCompleted) {
      return ScoringResult(
        state: _state,
        newEvents: const [],
        transitions: const [],
      );
    }
    final e = _make(
      MatchEventType.matchCompleted,
      teamId: winner,
      device: device,
      method: SourceMethod.manualEdit,
    );
    _events.add(e);
    _recompute();
    return ScoringResult(
      state: _state,
      newEvents: [e],
      transitions: const [ScoreTransition.matchWon],
    );
  }

  /// Manual score correction (long press on watch, PRD D1). Undoable.
  ScoringResult editScore({
    required int pointsA,
    required int pointsB,
    required int gamesA,
    required int gamesB,
    int? freePlayA,
    int? freePlayB,
    int? tieBreakA,
    int? tieBreakB,
    int? deuceNumber,
    SourceDevice device = SourceDevice.phone,
  }) {
    if (_state.status == MatchStatus.paused || _state.isCompleted) {
      return ScoringResult(
        state: _state,
        newEvents: const [],
        transitions: const [],
      );
    }
    final e = _make(
      MatchEventType.scoreEdited,
      device: device,
      method: SourceMethod.manualEdit,
      scoreBefore: _state.display,
      payload: {
        'pointsA': pointsA,
        'pointsB': pointsB,
        'gamesA': gamesA,
        'gamesB': gamesB,
        'freePlayA': ?freePlayA,
        'freePlayB': ?freePlayB,
        'tieBreakA': ?tieBreakA,
        'tieBreakB': ?tieBreakB,
        'deuceNumber': ?deuceNumber,
      },
    );
    _events.add(e);
    _recompute();
    _events[_events.length - 1] = e.copyWith(scoreAfter: _state.display);
    return ScoringResult(
      state: _state,
      newEvents: [_events.last],
      transitions: const [],
    );
  }

  ScoringResult _statusEvent(MatchEventType t, SourceDevice device) {
    final e = _make(t, device: device, method: SourceMethod.tap);
    _events.add(e);
    _recompute();
    return ScoringResult(state: _state, newEvents: [e], transitions: const []);
  }

  MatchEvent _make(
    MatchEventType type, {
    TeamId? teamId,
    SourceDevice device = SourceDevice.phone,
    SourceMethod method = SourceMethod.tap,
    String? scoreBefore,
    String? scoreAfter,
    Map<String, Object?>? payload,
  }) => MatchEvent(
    eventId: _newId(),
    matchId: matchId,
    timestampMs: _clock(),
    type: type,
    teamId: teamId,
    scoreBefore: scoreBefore,
    scoreAfter: scoreAfter,
    sourceDevice: device,
    sourceMethod: method,
    payload: payload,
    duoMode: duoMode,
    sourceUserId: sourceUserId,
    sourceTeamId: assignedTeam,
    createdLocallyAtMs: duoMode ? _clock() : null,
  );

  // ---------------------------------------------------------------- replay

  int _undoableCount() {
    var n = 0;
    final resolution = _resolveUndos();
    for (var i = 0; i < _events.length; i++) {
      switch (_events[i].type) {
        case MatchEventType.pointTeamA:
        case MatchEventType.pointTeamB:
        case MatchEventType.scoreEdited:
          if (!resolution.cancelled.contains(i) &&
              !resolution.ignored.contains(i)) {
            n++;
          }
        default:
          break;
      }
    }
    return n;
  }

  /// Pass 1 of the replay: resolves UNDOs → indices of cancelled events.
  ///
  /// A plain UNDO cancels the most recent still-active undoable event.
  /// An UNDO carrying a teamId (Duo Mode) cancels only the most recent
  /// still-active point of that team: the result is order-independent
  /// across devices that received the two teams' events interleaved
  /// differently.
  _UndoResolution _resolveUndos() {
    final cancelled = <int>{};
    final ignored = <int>{};
    final stack = <int>[];
    var lifecycle = MatchStatus.created;
    var manuallyCompleted = false;
    for (var i = 0; i < _events.length; i++) {
      final e = _events[i];
      switch (e.type) {
        case MatchEventType.matchStarted:
          if (lifecycle == MatchStatus.created) {
            lifecycle = MatchStatus.inProgress;
          }
        case MatchEventType.matchPaused:
          if (lifecycle == MatchStatus.inProgress) {
            lifecycle = MatchStatus.paused;
          }
        case MatchEventType.matchResumed:
          if (lifecycle == MatchStatus.paused) {
            lifecycle = MatchStatus.inProgress;
          }
        case MatchEventType.pointTeamA:
        case MatchEventType.pointTeamB:
          if (lifecycle == MatchStatus.completed) {
            ignored.add(i);
            break;
          }
          // Phone paused while watch still scores: treat remote points as
          // implicit resume instead of permanently dropping them (desync).
          if (lifecycle == MatchStatus.paused) {
            lifecycle = MatchStatus.inProgress;
          }
          if (lifecycle == MatchStatus.created) {
            lifecycle = MatchStatus.inProgress;
          }
          stack.add(i);
        case MatchEventType.scoreEdited:
          // Score edits while paused stay no-ops (local power-user path only
          // when match is live); only points auto-resume dual-device desync.
          if (lifecycle == MatchStatus.paused ||
              lifecycle == MatchStatus.completed) {
            ignored.add(i);
            break;
          }
          stack.add(i);
        case MatchEventType.matchCompleted:
          lifecycle = MatchStatus.completed;
          if (e.sourceMethod == SourceMethod.manualEdit) {
            manuallyCompleted = true;
          }
        case MatchEventType.undo:
          if (lifecycle == MatchStatus.paused) {
            ignored.add(i);
            break;
          }
          final team = e.teamId;
          final targetEventId = e.payload?['targetEventId']?.toString();
          var didCancel = false;
          // Prefer exact target when present (Garmin/Fitbit Duo undo).
          if (targetEventId != null && targetEventId.isNotEmpty) {
            for (var s = stack.length - 1; s >= 0; s--) {
              final candidate = _events[stack[s]];
              if (candidate.eventId != targetEventId) continue;
              if (team != null) {
                final wanted = team == TeamId.a
                    ? MatchEventType.pointTeamA
                    : MatchEventType.pointTeamB;
                if (candidate.type != wanted) continue;
              }
              cancelled.add(stack.removeAt(s));
              didCancel = true;
              break;
            }
          } else if (team == null) {
            if (stack.isNotEmpty) {
              cancelled.add(stack.removeLast());
              didCancel = true;
            }
          } else {
            final wanted = team == TeamId.a
                ? MatchEventType.pointTeamA
                : MatchEventType.pointTeamB;
            for (var s = stack.length - 1; s >= 0; s--) {
              if (_events[stack[s]].type == wanted) {
                cancelled.add(stack.removeAt(s));
                didCancel = true;
                break;
              }
            }
          }
          // An automatic completion is derived from the last point. Cancelling
          // that point reopens the match; a manual completion is not undoable.
          if (didCancel &&
              lifecycle == MatchStatus.completed &&
              !manuallyCompleted) {
            lifecycle = MatchStatus.inProgress;
          }
        default:
          break;
      }
    }
    return _UndoResolution(cancelled: cancelled, ignored: ignored);
  }

  /// Replays the raw log, rebuilding [_state] and [_records].
  /// Returns the transitions produced by the last effective action.
  List<ScoreTransition> _recompute() {
    final resolution = _resolveUndos();

    // Pass 2: sequential apply.
    final w = _WorkingState(format: format, firstServer: firstServer);
    final records = <PointRecord>[];
    var lastTransitions = <ScoreTransition>[];

    for (var i = 0; i < _events.length; i++) {
      final e = _events[i];
      if (resolution.cancelled.contains(i) || resolution.ignored.contains(i)) {
        continue;
      }
      switch (e.type) {
        case MatchEventType.matchStarted:
          if (w.status == MatchStatus.created) {
            w.status = MatchStatus.inProgress;
          }
        case MatchEventType.matchPaused:
          if (w.status == MatchStatus.inProgress) {
            w.status = MatchStatus.paused;
          }
        case MatchEventType.matchResumed:
          if (w.status == MatchStatus.paused) {
            w.status = MatchStatus.inProgress;
          }
        case MatchEventType.pointTeamA:
        case MatchEventType.pointTeamB:
          // Completed matches never accept points.
          if (w.status == MatchStatus.completed) {
            break;
          }
          // Journal from watch while phone was paused: resume then apply so
          // mid-match dual-device scoring does not permanently drop points.
          // Live API still refuses addPoint while paused (see addPoint).
          if (w.status == MatchStatus.paused) {
            w.status = MatchStatus.inProgress;
          }
          if (w.status == MatchStatus.created) {
            w.status = MatchStatus.inProgress;
          }
          final team = e.type == MatchEventType.pointTeamA
              ? TeamId.a
              : TeamId.b;
          final record = w.recordFor(team, records.length, e);
          lastTransitions = w.applyPoint(team);
          records.add(record.withScoreAfter(w.analyticsSnapshot()));
        case MatchEventType.scoreEdited:
          if (w.status == MatchStatus.paused ||
              w.status == MatchStatus.completed) {
            break;
          }
          w.applyEdit(e.payload ?? const {});
          lastTransitions = const [];
        case MatchEventType.matchCompleted:
          // Only explicit (manual) completions change state here; derived
          // ones were already produced by applyPoint.
          if (e.sourceMethod == SourceMethod.manualEdit &&
              w.status != MatchStatus.completed) {
            w.status = MatchStatus.completed;
            w.winner = e.teamId ?? w.leadingTeam();
            lastTransitions = const [ScoreTransition.matchWon];
          }
        case MatchEventType.undo:
        case MatchEventType.gameCompleted:
        case MatchEventType.setCompleted:
        case MatchEventType.sideChange:
        case MatchEventType.deviceJoinedMatch:
        case MatchEventType.deviceLeftMatch:
        case MatchEventType.teamConfirmed:
          break; // audit only
      }
    }

    _state = w.snapshot();
    _records = records;
    return lastTransitions;
  }

  /// Serialize the full log (sync payload phone ⇄ watch ⇄ cloud).
  List<Map<String, Object?>> eventsToJson() =>
      _events.map((e) => e.toJson()).toList();
}

// ------------------------------------------------------------------ private

class _WorkingState {
  _WorkingState({required this.format, required TeamId firstServer})
    : servingTeam = firstServer;

  final MatchFormat format;

  MatchStatus status = MatchStatus.created;
  int pointsA = 0, pointsB = 0; // 0..3, 4=advantage holder side
  int gamesA = 0, gamesB = 0;
  int setsA = 0, setsB = 0;
  final List<SetResult> completedSets = [];
  TeamId servingTeam;
  bool inTieBreak = false;
  bool inSuperTieBreak = false;
  int tbA = 0, tbB = 0;
  TeamId tbFirstServer = TeamId.a;
  int freeA = 0, freeB = 0;
  int deuceNumber = 0;
  int totalGamesPlayed = 0;
  bool sideChangePending = false;
  TeamId? winner;

  int get setIndex => setsA + setsB;
  int get gameIndexInSet => gamesA + gamesB;

  /// The set currently in play is the last one the match can have.
  bool get inDecidingSet =>
      setsA == format.setsToWin - 1 && setsB == format.setsToWin - 1;

  /// Whether gamesPerSet-all opens a tie-break in the set being played.
  /// FIP Rule 1, Option 1.4 allows the deciding set to be played out instead.
  bool get tieBreakAvailable =>
      format.tieBreakAtGamesAll &&
      (format.tieBreakInDecidingSet || !inDecidingSet);

  TeamId? leadingTeam() {
    if (format.freePlay) {
      if (freeA == freeB) return null;
      return freeA > freeB ? TeamId.a : TeamId.b;
    }
    if (setsA != setsB) return setsA > setsB ? TeamId.a : TeamId.b;
    if (gamesA != gamesB) return gamesA > gamesB ? TeamId.a : TeamId.b;
    return null;
  }

  // ----- decisive-point context (before the rally)

  Set<TeamId> _gamePointFor() {
    if (format.freePlay) return const {};
    if (inTieBreak || inSuperTieBreak) {
      final target = inSuperTieBreak
          ? format.superTieBreakPoints
          : format.tieBreakPoints;
      final s = <TeamId>{};
      if (tbA + 1 >= target && tbA + 1 - tbB >= 2) s.add(TeamId.a);
      if (tbB + 1 >= target && tbB + 1 - tbA >= 2) s.add(TeamId.b);
      return s;
    }
    final s = <TeamId>{};
    switch (format.gameScoringMode) {
      case GameScoringMode.goldenPoint:
        if (pointsA >= 3 && pointsB >= 3) return {TeamId.a, TeamId.b};
        if (pointsA == 3) s.add(TeamId.a);
        if (pointsB == 3) s.add(TeamId.b);
      case GameScoringMode.starPoint:
        if (pointsA == 3 && pointsB == 3 && deuceNumber >= 3) {
          return {TeamId.a, TeamId.b};
        }
        if (pointsA == 4) return {TeamId.a}; // Advantage 1/2 for A.
        if (pointsB == 4) return {TeamId.b};
        if (pointsA == 3 && pointsB < 3) s.add(TeamId.a);
        if (pointsB == 3 && pointsA < 3) s.add(TeamId.b);
      case GameScoringMode.advantage:
        if (pointsA == 4) return {TeamId.a}; // AD A
        if (pointsB == 4) return {TeamId.b};
        if (pointsA == 3 && pointsB < 3) s.add(TeamId.a);
        if (pointsB == 3 && pointsA < 3) s.add(TeamId.b);
    }
    return s;
  }

  bool _wouldWinSet(TeamId t) {
    if (inSuperTieBreak) return true;
    if (inTieBreak) return true;
    final g = t == TeamId.a ? gamesA : gamesB;
    final o = t == TeamId.a ? gamesB : gamesA;
    final afterG = g + 1;
    if (tieBreakAvailable && afterG > format.gamesPerSet) {
      return true; // winning the 7th game after 6-6 is impossible here, safe
    }
    return afterG >= format.gamesPerSet && afterG - o >= 2;
  }

  bool _wouldWinMatch(TeamId t) {
    final s = t == TeamId.a ? setsA : setsB;
    return s + 1 >= format.setsToWin;
  }

  PointRecord recordFor(TeamId winner, int index, dynamic event) {
    final gp = _gamePointFor();
    final sp = gp.where(_wouldWinSet).toSet();
    final mp = sp.where(_wouldWinMatch).toSet();
    final bp = (inTieBreak || inSuperTieBreak)
        ? <TeamId>{}
        : gp.where((t) => t != servingTeam).toSet();
    final deuce =
        !format.freePlay &&
        !inTieBreak &&
        !inSuperTieBreak &&
        pointsA >= 3 &&
        pointsB >= 3 &&
        pointsA == pointsB;
    return PointRecord(
      index: index,
      winner: winner,
      timestampMs: event.timestampMs as int,
      setIndex: setIndex,
      gameIndexInSet: gameIndexInSet,
      inTieBreak: inTieBreak,
      inSuperTieBreak: inSuperTieBreak,
      servingTeam: currentServer(),
      gamePointFor: gp,
      setPointFor: sp,
      matchPointFor: mp,
      breakPointFor: bp,
      isDeucePoint: deuce,
      isStarPoint:
          deuce &&
          format.gameScoringMode == GameScoringMode.starPoint &&
          deuceNumber >= 3,
      sourceDevice: event.sourceDevice as SourceDevice,
      sourceMethod: event.sourceMethod as SourceMethod,
      scoreBefore: analyticsSnapshot(),
      scoreAfter: analyticsSnapshot(),
    );
  }

  PointScoreSnapshot analyticsSnapshot() => PointScoreSnapshot(
    pointsA: pointsA,
    pointsB: pointsB,
    gamesA: gamesA,
    gamesB: gamesB,
    setsA: setsA,
    setsB: setsB,
    inTieBreak: inTieBreak,
    inSuperTieBreak: inSuperTieBreak,
    tieBreakA: tbA,
    tieBreakB: tbB,
    freePlayA: freeA,
    freePlayB: freeB,
    deuceNumber: deuceNumber,
    completed: status == MatchStatus.completed,
    winner: winner,
  );

  TeamId currentServer() {
    if (!inTieBreak && !inSuperTieBreak) return servingTeam;
    final idx = tbA + tbB;
    if (idx == 0) return tbFirstServer;
    final block = (idx - 1) ~/ 2;
    return block.isEven ? tbFirstServer.opponent : tbFirstServer;
  }

  // ----- apply

  List<ScoreTransition> applyPoint(TeamId team) {
    sideChangePending = false;
    if (format.freePlay) {
      if (team == TeamId.a) {
        freeA++;
      } else {
        freeB++;
      }
      return const [ScoreTransition.point];
    }
    if (inTieBreak || inSuperTieBreak) return _applyTieBreakPoint(team);
    return _applyGamePoint(team);
  }

  List<ScoreTransition> _applyGamePoint(TeamId team) {
    TeamId? gameWinner;
    switch (format.gameScoringMode) {
      case GameScoringMode.goldenPoint:
        if (team == TeamId.a) {
          pointsA++;
        } else {
          pointsB++;
        }
        if (pointsA >= 4 || pointsB >= 4) gameWinner = team;
      case GameScoringMode.advantage:
      case GameScoringMode.starPoint:
        final starPoint = format.gameScoringMode == GameScoringMode.starPoint;
        // Advantage and Star Point use the same explicit AD state. Star Point
        // permits only two advantage cycles; deuce 3 is a deciding rally.
        if (pointsA == 4 && pointsB == 3) {
          if (team == TeamId.a) {
            gameWinner = team;
          } else {
            pointsA = 3;
            pointsB = 3;
            if (starPoint) {
              deuceNumber = (deuceNumber + 1).clamp(1, 3);
            }
          }
        } else if (pointsB == 4 && pointsA == 3) {
          if (team == TeamId.b) {
            gameWinner = team;
          } else {
            pointsA = 3;
            pointsB = 3;
            if (starPoint) {
              deuceNumber = (deuceNumber + 1).clamp(1, 3);
            }
          }
        } else if (pointsA == 3 && pointsB == 3) {
          if (starPoint && deuceNumber >= 3) {
            gameWinner = team;
          } else if (team == TeamId.a) {
            pointsA = 4;
          } else {
            pointsB = 4;
          }
        } else {
          if (team == TeamId.a) {
            pointsA++;
          } else {
            pointsB++;
          }
          if (starPoint && pointsA == 3 && pointsB == 3 && deuceNumber == 0) {
            deuceNumber = 1;
          }
          if ((pointsA >= 4 && pointsA - pointsB >= 2) ||
              (pointsB >= 4 && pointsB - pointsA >= 2)) {
            gameWinner = team;
          }
        }
    }
    if (gameWinner == null) return const [ScoreTransition.point];

    final gWinner = gameWinner;
    pointsA = 0;
    pointsB = 0;
    deuceNumber = 0;
    if (gWinner == TeamId.a) {
      gamesA++;
    } else {
      gamesB++;
    }
    totalGamesPlayed++;
    servingTeam = servingTeam.opponent;

    final transitions = <ScoreTransition>[
      ScoreTransition.point,
      ScoreTransition.gameWon,
    ];

    // Set won outright? _completeSet owns the end-of-set change of ends, which
    // follows the same odd-total rule applied below to mid-set games.
    final leaderGames = gWinner == TeamId.a ? gamesA : gamesB;
    final otherGames = gWinner == TeamId.a ? gamesB : gamesA;
    if (leaderGames >= format.gamesPerSet && leaderGames - otherGames >= 2) {
      transitions.addAll(_completeSet(gWinner, tb: false));
      return transitions;
    }

    if ((gamesA + gamesB).isOdd) {
      sideChangePending = true;
      transitions.add(ScoreTransition.sideChange);
    }

    // Enter tie-break? Not in a deciding set played to two games of margin.
    if (tieBreakAvailable &&
        gamesA == format.gamesPerSet &&
        gamesB == format.gamesPerSet) {
      inTieBreak = true;
      tbA = 0;
      tbB = 0;
      tbFirstServer = servingTeam;
    }
    return transitions;
  }

  List<ScoreTransition> _applyTieBreakPoint(TeamId team) {
    if (team == TeamId.a) {
      tbA++;
    } else {
      tbB++;
    }
    final target = inSuperTieBreak
        ? format.superTieBreakPoints
        : format.tieBreakPoints;
    final transitions = <ScoreTransition>[ScoreTransition.point];

    final total = tbA + tbB;
    final leader = tbA > tbB ? TeamId.a : TeamId.b;
    final lead = (tbA - tbB).abs();
    final maxPts = tbA > tbB ? tbA : tbB;

    if (maxPts >= target && lead >= 2) {
      if (inSuperTieBreak) {
        transitions.addAll(_completeSuperTieBreak(leader));
      } else {
        transitions.add(ScoreTransition.gameWon);
        transitions.addAll(_completeSet(leader, tb: true));
      }
      return transitions;
    }
    if (total > 0 && total % 6 == 0) {
      sideChangePending = true;
      transitions.add(ScoreTransition.sideChange);
    }
    return transitions;
  }

  List<ScoreTransition> _completeSet(TeamId setWinner, {required bool tb}) {
    final result = tb
        ? SetResult(
            gamesA: setWinner == TeamId.a
                ? format.gamesPerSet + 1
                : format.gamesPerSet,
            gamesB: setWinner == TeamId.b
                ? format.gamesPerSet + 1
                : format.gamesPerSet,
            tieBreakA: tbA,
            tieBreakB: tbB,
          )
        : SetResult(gamesA: gamesA, gamesB: gamesB);
    completedSets.add(result);
    if (setWinner == TeamId.a) {
      setsA++;
    } else {
      setsB++;
    }
    gamesA = 0;
    gamesB = 0;
    pointsA = 0;
    pointsB = 0;
    deuceNumber = 0;
    if (inTieBreak) {
      // New set starts with the team that did not serve first in the TB.
      servingTeam = tbFirstServer.opponent;
    }
    inTieBreak = false;
    tbA = 0;
    tbB = 0;

    // FIP Rules of Padel (Rule 11 — Change of ends): teams change ends at the
    // end of every odd game, and at the end of a set only when the set's total
    // number of games is odd. After an even set (6-0, 6-2, 6-4) the change is
    // deferred to the end of the first game of the next set, which the
    // per-game odd rule in _applyGamePoint already produces. A set won on a
    // tie-break is 7-6 = 13 games, so it always changes ends.
    final setTotalGames = result.gamesA + result.gamesB;
    final changeEnds = setTotalGames.isOdd;
    sideChangePending = changeEnds;

    final transitions = <ScoreTransition>[ScoreTransition.setWon];
    if (changeEnds) transitions.add(ScoreTransition.sideChange);

    final winSets = setWinner == TeamId.a ? setsA : setsB;
    if (winSets >= format.setsToWin) {
      status = MatchStatus.completed;
      winner = setWinner;
      // The match is over: there is no next game to change ends for.
      sideChangePending = false;
      transitions.add(ScoreTransition.matchWon);
      return transitions;
    }

    // Deciding set replaced by super tie-break?
    if (format.superTieBreakDecider &&
        setsA == format.setsToWin - 1 &&
        setsB == format.setsToWin - 1) {
      inSuperTieBreak = true;
      tbA = 0;
      tbB = 0;
      tbFirstServer = servingTeam;
    }
    return transitions;
  }

  List<ScoreTransition> _completeSuperTieBreak(TeamId stbWinner) {
    completedSets.add(
      SetResult(
        gamesA: stbWinner == TeamId.a ? 1 : 0,
        gamesB: stbWinner == TeamId.b ? 1 : 0,
        tieBreakA: tbA,
        tieBreakB: tbB,
        isSuperTieBreak: true,
      ),
    );
    if (stbWinner == TeamId.a) {
      setsA++;
    } else {
      setsB++;
    }
    inSuperTieBreak = false;
    status = MatchStatus.completed;
    winner = stbWinner;
    return const [ScoreTransition.setWon, ScoreTransition.matchWon];
  }

  void applyEdit(Map<String, Object?> p) {
    pointsA = (p['pointsA'] as int?)?.clamp(0, 4) ?? pointsA;
    pointsB = (p['pointsB'] as int?)?.clamp(0, 4) ?? pointsB;
    // A deciding set without tie-break has no 7-game ceiling (8-6, 9-7, …),
    // so the bound follows the set actually in play instead of a constant.
    final maxGames = tieBreakAvailable
        ? format.gamesPerSet + 1
        : format.gamesPerSet * 4;
    gamesA = (p['gamesA'] as int?)?.clamp(0, maxGames) ?? gamesA;
    gamesB = (p['gamesB'] as int?)?.clamp(0, maxGames) ?? gamesB;
    if (format.freePlay) {
      freeA = (p['freePlayA'] as int?)?.clamp(0, 9999) ?? freeA;
      freeB = (p['freePlayB'] as int?)?.clamp(0, 9999) ?? freeB;
    }
    if (inTieBreak || inSuperTieBreak) {
      // Same bounds discipline as points/games above: a corrupted wire
      // payload must not inject negative or runaway tie-break scores.
      final target = inSuperTieBreak
          ? format.superTieBreakPoints
          : format.tieBreakPoints;
      tbA = (p['tieBreakA'] as int?)?.clamp(0, target + 10) ?? tbA;
      tbB = (p['tieBreakB'] as int?)?.clamp(0, target + 10) ?? tbB;
    }
    _normalizeEditedGamePoints(p['deuceNumber'] as int?);
  }

  void _normalizeEditedGamePoints(int? editedDeuceNumber) {
    if (format.freePlay ||
        inTieBreak ||
        inSuperTieBreak ||
        format.gameScoringMode == GameScoringMode.goldenPoint) {
      pointsA = pointsA.clamp(0, 3);
      pointsB = pointsB.clamp(0, 3);
      deuceNumber = 0;
      return;
    }

    // AD is valid only as 4-3 or 3-4. Normalize corrupted/legacy absolute
    // edits instead of letting 4-4 or 4-2 leak into replay.
    if (pointsA == 4 && pointsB == 4) {
      pointsA = 3;
      pointsB = 3;
    } else {
      if (pointsA == 4 && pointsB != 3) pointsA = 3;
      if (pointsB == 4 && pointsA != 3) pointsB = 3;
    }

    if (format.gameScoringMode != GameScoringMode.starPoint) {
      deuceNumber = 0;
      return;
    }

    final inDeucePhase =
        (pointsA == 3 && pointsB == 3) ||
        (pointsA == 4 && pointsB == 3) ||
        (pointsB == 4 && pointsA == 3);
    if (!inDeucePhase) {
      deuceNumber = 0;
      return;
    }

    // Legacy SCORE_EDITED events did not carry a phase. A 40-40 edit therefore
    // deterministically restarts from deuce 1 instead of inheriting stale state.
    deuceNumber = (editedDeuceNumber ?? 1).clamp(1, 3);
    if ((pointsA == 4 || pointsB == 4) && deuceNumber == 3) {
      // Deuce 3 is already the deciding Star Point and has no advantage state.
      deuceNumber = 2;
    }
  }

  MatchState snapshot() {
    TeamId? advantage;
    if (format.gameScoringMode != GameScoringMode.goldenPoint) {
      if (pointsA == 4 && pointsB == 3) advantage = TeamId.a;
      if (pointsB == 4 && pointsA == 3) advantage = TeamId.b;
    }
    return MatchState(
      status: status,
      points: GamePoints(
        pointsA.clamp(0, 3),
        pointsB.clamp(0, 3),
        advantage: advantage,
        deuceNumber: deuceNumber,
      ),
      gamesA: gamesA,
      gamesB: gamesB,
      setsA: setsA,
      setsB: setsB,
      completedSets: List.unmodifiable(completedSets),
      servingTeam: currentServer(),
      inTieBreak: inTieBreak,
      inSuperTieBreak: inSuperTieBreak,
      tieBreakA: tbA,
      tieBreakB: tbB,
      freePlayA: freeA,
      freePlayB: freeB,
      totalGamesPlayed: totalGamesPlayed,
      sideChangePending: sideChangePending,
      winner: winner,
    );
  }
}
